### PR TITLE
added few extensions

### PR DESCRIPTION
**Pull request by ircbloqcc**
1. Blynk IOT
2. AdafruitIO
3. ThingSpeak
4. LocalServer (Web Server)
5. Joystick Shield V1.A
6. Motor Shield V1.0

### CODE REVIEW

**Comment by zhengyangliu** [comment]
Oh, old friend, there's so much content here. Have you tested the usability of these extensions? 'll just merge if you've tested it.

**Comment by ircbloqcc** [comment]
yes, i worked with these. all works. but i didnt do with Chinese language.  You can translate.

**Comment by ircbloqcc** [comment]
pls check below screenshots

Screenshot 2022-03-11 104242
Screenshot 2022-03-11 104340
Screenshot 2022-03-11 104408
Screenshot 2022-03-11 104435
Screenshot 2022-03-11 104452

**Comment by ircbloqcc** [comment]
OLED Extension

Screenshot 2022-03-11 104707

**Comment by zhengyangliu** [comment]
In addition, there are some problems with the previous pr about maxduino and pico. You pushed a lot of changes, but didn't follow the code format, I had a hard time merging, could you try splitting these commits into stages to merge. and it is recommended that you install an eslint plugin to automatically format code.

**Comment by ircbloqcc** [comment]
Actually i didnt use vs code. i just copied the code from microbit and edited the code. Really i dont know javascript. just  doing reverse engineering of your code. Let me try.

**Comment by zhengyangliu** [comment]
Let me think about it, or I create a branch and merge it bit by bit.

**Pull request merged**
